app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('members/', include('members.urls'))
]

app/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_todo/', views.add_todo, name='add-todo'),
    path('update_todo/<int:pk>/', views.update_todo, name='update-todo'),
    path('delete_todo/<int:pk>/', views.delete_todo, name='delete-todo'),
    path('check_todo/<int:pk>/', views.check_todo, name='check-todo'),
]

app/members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout')
]

app/main/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Todo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title, self.text

app/members/models.py
from django.db import models

# Create your models here.

app/main/views.py
from django.shortcuts import render, redirect

# Create your views here.
from main.models import Todo


def index(request):
    order = request.GET.get('order')
    completed = request.GET.get('completed')
    search_text = request.GET.get('search_text')

    if order is None:
        order = '-created'

    query = Todo.objects.all().order_by(order)

    if search_text:
        todo_items = query.filter(text__contains=search_text)
    else:
        todo_items = query

    if completed:
        todo_items = query.filter(status=completed)

    context = {
        'todo_items': todo_items,
    }
    return render(request, 'main/index.html', context)


def add_todo(request):
    if request.method == 'POST':
        author = request.user
        text = request.POST['text']
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']

        Todo.objects.create(author=author, text=text, start_date=start_date, end_date=end_date)
        return redirect('main:index')
    else:
        return render(request, 'main/add_todo.html')


def update_todo(request, pk):
    todo = Todo.objects.get(pk=pk)

    if request.method == 'POST':
        todo.text = request.POST['text']
        todo.start_date = request.POST['start_date']
        todo.end_date = request.POST['end_date']
        todo.save()
        return redirect('main:index')
    else:
        context = {
            'todo': todo
        }
        return render(request, 'main/update_todo.html', context)


def delete_todo(request, pk):
    Todo.objects.get(pk=pk).delete()
    return redirect('main:index')


def check_todo(request, pk):
    todo = Todo.objects.get(pk=pk)
    if todo.status:
        todo.status = False
        todo.save()
    else:
        todo.status = True
        todo.save()
    return redirect('main:index')

app/members/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('main:index')
        else:
            raise ValidationError('username 또는 password가 틀립니다.')
            return redirect('members:signin')
    else:
        return render(request, 'members/signin.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        users = User.objects.all()

        if users.filter(username=username):
            return HttpResponse('이미 사용중인 username 입니다.')
        else:
            user = User.objects.create_user(username=username, password=password)
            login(request, user)
            return redirect('main:index')
    else:
        return render(request, 'members/signup.html')


def signout(request):
    logout(request)
    return redirect('main:index')

app/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css.map' %}">
    {% block head %}
    {% endblock %}
</head>

{% block content %}
{% endblock %}
</html>

app/templates/main/add_todo.html
{% extends 'base.html' %}

{% block head %}
<style>
    body {
        width: 400px;
        margin: 100px auto;
        background-color: #f5f5f5;
    }

    h2 {
        margin-bottom: 20px;
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<body>
<h2 class="display-4 font-weight-normal">Add Todo</h2>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="text">할 일</span>
        </div>
        <input type="text" name="text" class="form-control" aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-default">
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="start_date">시작 날짜</span>
        </div>
        <input type="text" onfocus="(this.type='date')" name="start_date" class="form-control"
               aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-default">
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="end_date">끝나는 날짜</span>
        </div>
        <input type="text" onfocus="(this.type='date')" name="end_date" class="form-control"
               aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-default">
    </div>
    <button type="submit" class="btn btn-outline-info">Submit</button>
</form>
</body>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block head %}
<style>
    li {
        list-style: none;
        display: inline-block;
    }
</style>
{% endblock %}

{% block content %}
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main:index' %}">My Todos</a>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:add-todo' %}">+Add Todo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:signin' %}">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:signout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:signup' %}">가입하기</a>
            </li>
        </ul>

        <form action="{% url 'main:index' %}" method="get" class="form-inline mt-2 mt-md-0">
            <input name="search_text" type="text" class="form-control mr-sm-2">
            <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>
        </form>
    </div>
</nav>

<div class="jumbotron" style="height: 100vh;">
    <div class="alert alert-success" role="alert">
        <strong>Hello {{ request.user }}!</strong> 당신의 Todo를 추가해 보세요!
    </div>

    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="text-muted" href="?order=start_date">시작날짜순</a>
                <a class="text-muted" href="?order=-end_date">끝나는날짜순</a>
                <a class="text-muted" href="?completed=True">완료</a>
                <a class="text-muted" href="?completed=False">미완료</a>
            </div>
        </div>

    </header>

    <ul style="padding: 0;">
        {% for todo_item in todo_items %}
        {% if todo_item.author == request.user %}
        <li>
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    {% if todo_item.status %}
                    <a href="{% url 'main:check-todo' pk=todo_item.pk %}" class="btn btn-success btn-sm mb-2">완료</a>
                    {% else %}
                    <a href="{% url 'main:check-todo' pk=todo_item.pk %}" class="btn btn-secondary btn-sm mb-2">미완료</a>
                    {% endif %}

                    <h5 class="card-title">{{ todo_item.text }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ todo_item.start_date }} ~ {{ todo_item.end_date }}</h6>
                    <a href="{% url 'main:delete-todo' pk=todo_item.pk %}" class="card-link">Delete</a>
                    <form action="" method="get">
                        {% csrf_token %}
                        <a href="{% url 'main:update-todo' pk=todo_item.pk %}" class="card-link">Update</a>
                    </form>
                </div>
            </div>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>
</body>
{% endblock %}

app/templates/main/update_todo.html
{% extends 'base.html' %}

{% block head %}
<style>
    body {
        width: 400px;
        margin: 100px auto;
        background-color: #f5f5f5;
    }

    h2 {
        margin-bottom: 20px;
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<body>
<h2 class="display-4 font-weight-normal">Update Todo</h2>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="text">할 일</span>
        </div>
        <input type="text" name="text" value="{{ todo.text }}" class="form-control" aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-default">
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="start_date">시작 날짜</span>
        </div>
        <input type="text" onfocus="(this.type='date')" name="start_date" value="{{ todo.start_date }}" class="form-control"
               aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-default">
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="end_date">끝나는 날짜</span>
        </div>
        <input type="text" onfocus="(this.type='date')" name="end_date" value="{{ todo.end_date }}" class="form-control"
               aria-label="Sizing example input"
               aria-describedby="inputGroup-sizing-default">
    </div>
    <button type="submit" class="btn btn-outline-info">Submit</button>
</form>
</body>
{% endblock %}

app/templates/members/signin.html
{% extends 'base.html' %}

{% block head %}
<style>
    .text-center {
        margin-top: 200px;
        width: 400px;
        background-color: #f5f5f5;
    }
</style>
{% endblock %}

{% block content %}
<body class="text-center mx-auto text-center">
<form class="form-signin m-3" action="{% url 'members:signin' %}" method="post">
    {% csrf_token %}
    <h1 class="h3 m-3 font-weight-normal">로그인</h1>

    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" id="inputUsername" class="form-control m-2" placeholder="Username" required
           autofocus>

    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control m-2" placeholder="Password" required>

    <button class="btn btn-primary m-2" type="submit">로그인</button>
    <a href="{% url 'members:signup' %}" class="btn btn-outline-primary m-2">가입하기</a>
</form>
</body>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}

{% block head %}
<style>
    .text-center {
        margin-top: 200px;
        width: 400px;
        background-color: #f5f5f5;
    }
</style>
{% endblock %}

{% block content %}
<body class="text-center mx-auto text-center">
<form class="form-signin m-3" action="{% url 'members:signup' %}" method="post">
    {% csrf_token %}
    <h1 class="h3 m-3 font-weight-normal">가입하기</h1>

    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" id="inputUsername" class="form-control m-2" placeholder="Username" required
           autofocus>

    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control m-2" placeholder="Password" required>

    <button class="btn btn-primary m-2" type="submit">가입하기</button>
</form>
</body>
{% endblock %}